# Starter pipeline

trigger:
- master
- release/*

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      vmImage: windows-latest

    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK 8'
      inputs:
        packageType: 'sdk'
        version: '8.0.x'

    - script: dotnet --version
      displayName: 'Verify SDK version'

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: build
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: test
        projects: '**/*.csproj'